env:
  es6: true
  jest/globals: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
  - prettier
  - prettier/@typescript-eslint
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - jest
  - "@typescript-eslint"
settings:
  import/resolver:
    "node": { "extensions": [".js", ".jsx", ".json", ".ts", ".tsx"] }
